#!/bin/bash

isplaying=$(cat ~/.config/pianobar/isplaying)
nowplaying=$(cat ~/.config/pianobar/nowplaying)
if [ "$isplaying" = "0" ]
then
  mus(){ # Current song ..
    mus=`mpc current`
    if [[ $mus ]]; then
      mp3=$(tr '\n' ' ' | grep -Po '.*(?= \[playing\])|paused' | tr -d '\n' | cut -c 1-45 | cut -f-7 -d" " | tr -d ',)(/\`[]' | tr -d "-" | cut -f1 -d"." )
      case $mp3 in
        *MP3)
          title=$(for i in $mp3; do    echo "$mp3   "; done | rev | cut -c 4- | rev;) 
      ;;
      *)
        title=$(for i in $mp3; do    echo "$mp3   "; done)
      ;;
    esac
    echo "$title"
    fi
  }

  echo "$(MPD_HOST=127.0.0.1 mpc $password status | mus)"
else
  echo "$nowplaying  "
fi