#!/usr/bin/env python3
#
# A battery indicator blocklet script for i3blocks

from subprocess import check_output

status = check_output(['acpi'], universal_newlines=True)
state = status.split(": ")[1].split(", ")[0]
commasplitstatus = status.split(", ")
percentleft = int(commasplitstatus[1].rstrip("%\n"))

FA_LIGHTNING = "<span font='FontAwesome'>\uf0e7</span>"
FA_PLUG = "<span font='FontAwesome'>\uf1e6</span>"

fulltext = "<span>{}</span>".format(FA_LIGHTNING)
timeleft = ""

if state == "Discharging":
    time = commasplitstatus[-1].split()[0]
    #time = ":".join(time.split(":")[0:2])
    timeleft = "{}".format(time)
else:
    fulltext += " " + FA_PLUG

print(fulltext)
print(fulltext)