#!/usr/bin/env python3
#
# A battery indicator blocklet script for i3blocks

from subprocess import check_output

status = check_output(['acpi'], universal_newlines=True)
state = status.split(": ")[1].split(", ")[0]
commasplitstatus = status.split(", ")
percentleft = int(commasplitstatus[1].rstrip("%\n"))

FA_BATT = "<span font='FontAwesome'>\uf240</span>"
FA_PLUG = "<span font='FontAwesome'>\uf1e6</span>"

fulltext = "<span>{}</span>".format(FA_BATT)
timeleft = ""

if state == "Discharging":
    fulltext = "<span>{}</span>".format(FA_BATT)
else:
    fulltext = "<span>{}</span>".format(FA_PLUG)

form =  '<span>{}</span>'
fulltext += form.format(percentleft)

print(fulltext)
print(fulltext)