#!/bin/sh
#   ▗   ▗
# ▛▘▜▘▀▌▜▘▌▌▛▘
# ▄▌▐▖█▌▐▖▙▌▄▌ - Display status in one line, to be embedded on statuslines.
# ==============================================================================

# Thank to xero's script sysinfo
#	http://git.io/v4aH5

# Thank to z3bra's mkbar translated now in C
#	http://git.z3bra.org/mkb/files.html

battery=/sys/class/power_supply/BAT1
FULL=${FULL-█}
EMPTY=${EMPTY-░}
SIZE=${SIZE-10}

draw()
{
	perc=$1
	size=$2

	inc=$(( perc * size / 100 ))

	for v in $(seq 0 $(( size - 1 )))
	do
		[ "$v" -le "$inc" ] \
			&& out="${out}${FULL}" \
			|| out="${out}${EMPTY}"
	done

	printf '%s' "$out"
}

cpu()
{
	cpu="$(grep 'cpu ' /proc/stat |\
		awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')"
	cpu=$(printf "%.0f" $cpu)

	printf '%-2s %s' "c$cpu" "$(draw $cpu $SIZE)"
}

ram()
{
	ram="$(free | awk '/Mem:/ {print int($3/$2 * 100.0)}')"

	printf "%-2s %s" "r$ram" "$(draw $ram $SIZE)"
}

temperature()
{
	temp="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))"

	printf "%-2s %s" "t$temp" " $(draw $temp $SIZE)"
}

printf ' %s  %s  %s\n' \
	"$(temperature)" "$(cpu)" "$(ram)"